# **PyTorch**

**Two important features of Pytorch are: **

 **1. *GPU acceleration*  **
   
 **2. *Autograd * **

**Tensors** : Can be thought of like large dimensional matrices

# Import libraries

In [0]:
import numpy as np
import torch
import matplotlib.pyplot as plt

# Simple Tensor Operations

In [3]:
x=torch.zeros(3,2)
y=torch.ones(2,1)
z=torch.rand(3,3)
print(x)
print(y)
print(z)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1.],
        [1.]])
tensor([[0.3642, 0.2997, 0.6798],
        [0.6587, 0.1626, 0.5145],
        [0.3488, 0.4187, 0.9535]])


In [4]:
torch.empty(3,3)

tensor([[1.9003e-36, 0.0000e+00, 2.6625e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [3.0601e+32, 1.8179e+31, 2.7947e+20]])

In [5]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
torch.linspace(0,10,steps=6)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [7]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

# Slicing tensors

In [8]:
z

tensor([[0.3642, 0.2997, 0.6798],
        [0.6587, 0.1626, 0.5145],
        [0.3488, 0.4187, 0.9535]])

In [9]:
z.size()

torch.Size([3, 3])

In [10]:
z[:2,:]

tensor([[0.3642, 0.2997, 0.6798],
        [0.6587, 0.1626, 0.5145]])

In [11]:
z[1:,:-1]

tensor([[0.6587, 0.1626],
        [0.3488, 0.4187]])

In [0]:
a=z[2,2]

In [13]:
a

tensor(0.9535)

In [14]:
a.item()

0.9534729719161987

# Reshaping

In [0]:
b=z[:2,:]

In [16]:
b.size()

torch.Size([2, 3])

In [17]:
b.view(3,2)

tensor([[0.3642, 0.2997],
        [0.6798, 0.6587],
        [0.1626, 0.5145]])

In [18]:
b.view(6,-1)

tensor([[0.3642],
        [0.2997],
        [0.6798],
        [0.6587],
        [0.1626],
        [0.5145]])

# Simple operations

In [0]:
x=torch.ones(3,2)
y=torch.ones(3,2)

In [20]:
x+y

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [21]:
x-y

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
x*y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [23]:
x/y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [24]:
z=x.add(y)

print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [0]:
# inplace, x also gets updated as z
z=x.add_(y)

In [26]:
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


# Torch and Numpy

In [0]:
x_np=x.numpy()

In [28]:
type(x),type(x_np)

(torch.Tensor, numpy.ndarray)

In [0]:
x_t=torch.from_numpy(x_np)

In [30]:
type(x_t)

torch.Tensor

In [0]:
# If I update x_t , note that x also gets updated simultaneously

In [32]:
%%time

for i in range(100):
  a=np.random.randn(100,100)
  b=np.random.randn(100,100)
  c=a+b
  

CPU times: user 84.2 ms, sys: 564 µs, total: 84.8 ms
Wall time: 96.8 ms


In [33]:
%%time

for i in range(100):
  a=torch.rand(100,100)
  b=torch.rand(100,100)
  c=a+b

CPU times: user 14.3 ms, sys: 1.63 ms, total: 15.9 ms
Wall time: 18.9 ms


# As you can see, even with CPU compute, pytorch is way faster then numpy

# GPU Support

In [34]:
print(torch.cuda.device_count())

1


In [35]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla T4


In [0]:
cuda0=torch.device('cuda:0')

In [37]:
a=torch.ones(3,2,device=cuda0)
b=torch.ones(3,2,device=cuda0)
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


# numpy vs pytorch_cpu and pytorch_gpu

In [41]:
%%time

for i in range(100):
  a=np.random.randn(1000,1000)
  b=np.random.randn(1000,1000)
  c=np.add(b,a)

CPU times: user 8.62 s, sys: 28.4 ms, total: 8.65 s
Wall time: 8.65 s


In [42]:
%%time

for i in range(100):
  a=torch.randn([1000,1000])
  b=torch.randn([1000,1000])
  c=b.add_(a)

CPU times: user 1.7 s, sys: 18.4 ms, total: 1.72 s
Wall time: 1.72 s


In [43]:
%%time

for i in range(100):
  a=torch.randn([1000,1000],device=cuda0)
  b=torch.randn([1000,1000],device=cuda0)
  c=b.add_(a)

CPU times: user 3.42 ms, sys: 3.93 ms, total: 7.35 ms
Wall time: 15.6 ms


# WOW! 

# Automatic differentiation

Simulation of a forward pass and a backward pass(automatic)

In [49]:
x=torch.ones(3,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [50]:
y=x+5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [51]:
z=y*y+1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [52]:
t=torch.sum(z)
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [0]:
t.backward()

In [54]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])
